- name: Install all security, critical, and rollup updates without a scheduled task
  win_updates:
    category_names:
      - Definition Updates
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    state: installed
    reboot: yes
    reboot_timeout: 600
